package lnmpro;

import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;
import lnmpro.Commands.*;
import lnmpro.Listeners.*;

public final class Main extends JavaPlugin {

    private static Main instance;

    @Override
    public void onEnable() {
        instance = this;
        getCommand("duel").setExecutor(new DuelsCommand(this));
        getCommand("acceptduel").setExecutor(new AcceptDuelCommand(this));
        getCommand("denyduel").setExecutor(new DenyDuelCommand(this));
        Bukkit.getPluginManager().registerEvents(new DuelRequestListener(this), this);
    }

    public static Main getInstance() {
        return instance;
    }
}